### ISSUE TITLE
Pipeline support on 1.1.7

### ISSUE THREAD

**Issue by singha24** [vipinsthename/environment-dashboard#152] opened 2019-07-31 10:01 UTC
Hi team, thank you for your hard work on this plugin. 

I am trying to use the pipeline syntax in a pipeline however I keep getting the following error
`Undefined section "environmentDashboard"`

I have also tried adding inside steps{} with the following error
`No such DSL method 'environmentDashboard' found among steps`

Could you please show examples of it's usage in the read me or advise otherwise?

**Comment by willwh** [comment] 2019-08-06 14:41
Duplicate of #150.

**Closed by willwh** 2019-08-06 14:41 UTC
