### ISSUE TITLE
Dashboard is always too wide for browser (Chrome, Firefox)

### ISSUE THREAD

**Issue by dhildebrandt** [vipinsthename/environment-dashboard#50] opened 2015-08-12 22:12 UTC
The last column of my three-environment dashboard is always off the right side of the browser display window.  It can be side-scrolled in but this is undesirable.
Before scroll:
![jenkins](https://cloud.githubusercontent.com/assets/1693961/9238041/1c36b634-4104-11e5-8e10-da6fc5634b73.jpg)

After scroll:
![jenkins](https://cloud.githubusercontent.com/assets/1693961/9238022/012d797c-4104-11e5-9e47-751cbdb113ea.jpg)

After resize, individual columns are wider; same effect:
![jenkins](https://cloud.githubusercontent.com/assets/1693961/9238046/364c4c00-4104-11e5-987e-17f6b65399ab.jpg)

**Comment by vipinsthename** [comment] 2015-08-13 09:10
Which version of the plugin is this?

And which version of Jenkins? I ll try and reproduce the error :)

**Comment by dhildebrandt** [comment] 2015-08-13 17:44
Hi Vipin,

Plugin is v 1.1.3
Jenkins is 1.620

Thank you!!

-dave

**Comment by skarap** [comment] 2015-08-19 14:03
Looks like it thinks the toolbar on the left is removed - so can use whole screen, but in fact the space of the toolbar is left clean.

**Comment by vipinsthename** [comment] 2015-08-25 09:45
Release 1.1.4 should now fix this issue, let me know if you face any issues.

Else I ll close this issue.

**Comment by skarap** [comment] 2015-08-25 09:59
Fixed for me. Thanks!

**Comment by vipinsthename** [comment] 2015-08-25 10:03
Awesome! :)

Closing the issue.

**Closed by vipinsthename** 2015-08-25 10:03 UTC

**Comment by dhildebrandt** [comment] 2015-08-25 21:57
Just picked it up.  Awesome!

**Comment by SausagePie** [comment] 2016-09-10 08:23
This is a problem for me with Jenkins 2.21 and version 1.1.4 of this plugin.
@vipinsthename will you reopen this ticket or shall I create another?
Thanks!

**Comment by akhilkumar2601** [comment] 2020-03-03 07:34
hey @dhildebrandt how did you configure your job or components with this dashboard. Did you get the job configuration section after installing the plugin?Can you please help me?
